from Constants import *
TRANSLAITS = {
    'filing_lawsuit_date' : 'Дата подання позову',
    'receipt_decision_date': 'Дата отримання рішення суду',
    'message_send_date': 'Дата надіслання повідомлення',
    'appeal_proceedings': 'Апеляційне провадження',
    'cassation_proceedings':'Касаційне провадження',
    'referral_rwdws_date':'Дата направлення до РВ ДВС',
    'return_rwdws_date':'Дата повернення з РВ ДВС',
    'enforcement_court_decision_date':'Дата примусового виконання рішення суду',
    'case_number':'Номер справи',
    'resolution_number':'Номер постанови',
    'ruling_date':'Дата постанови',
    'administrative_commission':'Адмінкомісія',
    'incoming_claim_number':'Номер вхідного позову',
    'incoming_lawsuit_date':'Дата вхідного позову',
    'securing_claim':'Забезпечення позову',
    'is_decision':'Рішення прийнято',
    'agreement_date':'Дата домовленості',
    'term_end':'Кінець строку',
    'term_begin':'Початок строку',
    'issuance_deadline':'Термін видачі',
    'execution_date':'Дата виконання',
    'invoice_date':'Дата рахунку',
    'approval_date':'Дата затвердження',
    'none':'Відсутні дані',
    'vid_porushennya':'Вид порушення',
    'protocol_date':'Дата протоколу',
    'protocol_num':'Номер протоколу',
    'nachisleno':'Нараховано, грн із ПДВ',
    'oplatcheno':'Сплачено, грн',
    'ostatok':'Заборгованість, грн із ПДВ',
    str(BACK_TITLE):'Повернутись до попереднього меню?',
    str(FROM_DB):'Дані надано базою',
    str(IS_DEBTORS):'Порушення',
    str(ORDER_MENU):'Наряд-завдання',
    str(DEBTORS):'Порушники',
    str(SETTLEMENTS): 'Населені пункти',
    str(DISTRICTS):'Дільниці',
    str(IS_DISTRICT):'Дільниця',
    str(IS_GRP_SHRP):'1С МСБУ ГРП та ШРП',
    str(IS_WEBS):'1С МСБУ Газові мережі',
    str(IS_EZH):'Електро-хімзахист',
    str(CARD_LIST):'Перелік карточок користувача',
    str(COMMENTS):'Коментар',
    str(SUSTAIN):'Стан',
    str(INV_NUMBER):'Інвентарний номер',
    str(LATITUDE):'Широта',
    str(LONGITUDE):'Довгота',
    str(PHONE):'Номер телефону',
    str(COORDINATES):'Кординати об\'єкту',
    str(SETTLEMENT):'Населений пункт',
    str(LOCATION):'Адреса або місцезнаходження',
    str(CITY):'Місто',
    str(TYPE):'Тип об\'єкту',
    str(CATEGORIE):'Категогія об\'єкту',
    str(VALUE):'Значення',
    str(BEGIN):'Початок',
    str(END):'Кінець',
    str(IS_PARAM):'Параметр',
    str(IS_VALUE):'Значення',
    str(INDEX):'Ключ',
    str(TITLE):'Найменування',
    str(SUB_MENU):'Підменю',
    str(WORK_ORDERS):'Наряди',
    str(OBJECT_PARAMS):'Параметри об\'єкту',
    str(OBJECTS):'Об\'єкти',
    str(ORDER_TYPES):'Напрями робіт',
    str(DB_CHOSE):'Вибір бази даних',
    str(MAIN):'Головне меню',
    str(BACK):'Попередній пункт',
    str(EZH_SUSTAIN_TYPES):'Стан об\'єкту',
    str(PHOTO): 'Фото об\'єкту',
    str(ELECTRICITY_METER_READING): 'Показник електричного лічильника'
    }
